### ISSUE TITLE
Textures bleeding on the edges

### ISSUE THREAD

**Issue by lukas-kirschner** [lukas-kirschner/Exodus#3] opened 2022-11-04 09:58 UTC
![Screenshot_20221104_105533](https://user-images.githubusercontent.com/1347228/199945190-c240e3f0-0bdf-4914-81f5-b5d1e9248cc1.png)

Seems to be a bug in Bevy: https://github.com/bevyengine/bevy/issues/4748

A possible solution would be to put every tile into its own image file and stitching those together in a texture atlas later

**Comment by lukas-kirschner** [comment] 2022-11-04 09:59
Adding `.insert_resource(Msaa { samples: 1 })` does NOT fix the problem

**Comment by Semptic** [comment] 2022-11-16 21:34
Hi, I discovered your bug while I was looking for the same issue as you. I could "fix" it in my case by offsetting my tiles by
```
x: 0.6
y: 0.5
``` 
setting `.insert_resource(Msaa{ samples: 1 })`
and rounding my camera x and y postions e.g.
```
camera_transform.translation.x = player_transform.translation.x.round();
camera_transform.translation.y = player_transform.translation.y.round();
```
I only started 1 week ago with game and bevy development. Therefore I don't really understand why this is fixing it and if this is working on other machines too. Just read on a post about unity that there is an issue if your camera is not aligned to full pixels. Through this I started to play around with offsetting my tiles which in the end removed the lines for me. :shrug: The issue is not fixed by this. If I change the scale the lines appear again, but maybe this is helpful to you so you could find a solution to it.

**Comment by lukas-kirschner** [comment] 2022-11-20 11:00
Hi @Semptic , thank you very much for your suggestion! :smiley: I'll definitely try if it works for Exodus if I apply a rounding function to the camera position - Setting the MSAA did not do the trick for me, but maybe the two fixes in combination will. I suspect the bleeding textures are a GPU problem, so even if it works on my test system after applying those fixes, it might still bleed through on other ("more exotic") systems - I'll need to try running my game on different machines.

**Comment by lukas-kirschner** [comment] 2022-11-24 11:26
I managed to fix the texture bleeding, at least on my test laptop.
It seems I needed to apply a combination of `ImageSettings`, `FilterMode` and `MSAA`:

```rust
.insert_resource(ImageSettings::default_nearest())
.insert_resource(FilterMode::Nearest)
.insert_resource(Msaa { samples: 1 })
```

**Comment by lukas-kirschner** [comment] 2022-12-17 17:44
Unfortunalely, setting the texture size to 16 pixels in 73f0aff5b45f5a620262f71629b56214b70734a4 caused the problem to re-appear

**Comment by lukas-kirschner** [comment] 2023-02-18 12:36
I managed to fix the problem by rendering the world into a low-resolution texture and displaying this texture as sprite through the main camera. This approach may cause some programming and run-time overhead, but seems to work platform-independently. [This commit](https://github.com/lukas-kirschner/Exodus/commit/534c5ca32935299e134967285dca5f3c7b14c057) shows the changes I had to introduce to my game

**Closed** 2023-02-18 16:17 UTC
Labels: bug
